# Generated by Django 3.2 on 2021-04-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210430_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_key',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album_key',
            new_name='album_id',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='artist_key',
            new_name='artist_id',
        ),
    ]
