# Generated by Django 3.2 on 2021-04-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210430_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='times_playes',
            new_name='times_played',
        ),
    ]
